on:
  push:
    branches:
    - main
    - test_build.log
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-1
        id: checkout-dproc
        uses: actions/checkout@v4

      - name: checkout 2
        id: checkout-erosion3d
        uses: actions/checkout@v4
        with:
          repository: jonaslenz/toolbox.e3d
          ref: use_e3d_service

      - name: write build.log file
        run: |
          cat <<EOF > build.log
          erosion-3d: ref "${{ steps.checkout-erosion3d.outputs.ref }}", commit "${{ steps.checkout-erosion3d.outputs.commit }}"
          dproc: ref "${{ steps.checkout-dproc.outputs.ref }}", commit "${{ steps.checkout-dproc.outputs.commit }}"
          EOF

          echo "cat build.log"
          cat build.log
